[2025-04-28T13:30:38.732+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-28T13:30:38.764+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scheduler_crawling.transform_post manual__2025-04-28T13:25:01.396662+00:00 [queued]>
[2025-04-28T13:30:38.780+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scheduler_crawling.transform_post manual__2025-04-28T13:25:01.396662+00:00 [queued]>
[2025-04-28T13:30:38.783+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2025-04-28T13:30:38.804+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): transform_post> on 2025-04-28 13:25:01.396662+00:00
[2025-04-28T13:30:38.818+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1439) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-28T13:30:38.821+0000] {standard_task_runner.py:72} INFO - Started process 1441 to run task
[2025-04-28T13:30:38.821+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scheduler_crawling', 'transform_post', 'manual__2025-04-28T13:25:01.396662+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/job_post.py', '--cfg-path', '/tmp/tmpsu_0d_k0']
[2025-04-28T13:30:38.823+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask transform_post
[2025-04-28T13:30:38.905+0000] {task_command.py:467} INFO - Running <TaskInstance: scheduler_crawling.transform_post manual__2025-04-28T13:25:01.396662+00:00 [running]> on host 74add6dc246e
[2025-04-28T13:30:39.338+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scheduler_crawling' AIRFLOW_CTX_TASK_ID='transform_post' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T13:25:01.396662+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T13:25:01.396662+00:00'
[2025-04-28T13:30:39.341+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-28T13:30:39.342+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-28T13:30:39.343+0000] {logging_mixin.py:190} INFO - Current task name:transform_post state:running start_date:2025-04-28 13:30:38.765305+00:00
[2025-04-28T13:30:39.345+0000] {logging_mixin.py:190} INFO - Dag name:scheduler_crawling and current dag run status:running
[2025-04-28T13:30:39.346+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-28T13:30:39.357+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/job_post.py", line 61, in job_post
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-04-28T13:30:39.383+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-28T13:30:39.388+0000] {logging_mixin.py:190} INFO - Task start:2025-04-28 13:30:38.765305+00:00 end:2025-04-28 13:30:39.382432+00:00 duration:0.617127
[2025-04-28T13:30:39.393+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): transform_post> dag:<DAG: scheduler_crawling> dagrun:<DagRun scheduler_crawling @ 2025-04-28 13:25:01.396662+00:00: manual__2025-04-28T13:25:01.396662+00:00, state:running, queued_at: 2025-04-28 13:30:25.223563+00:00. externally triggered: True>
[2025-04-28T13:30:39.396+0000] {logging_mixin.py:190} INFO - Failure caused by Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-04-28T13:30:39.397+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=scheduler_crawling, task_id=transform_post, run_id=manual__2025-04-28T13:25:01.396662+00:00, execution_date=20250428T132501, start_date=20250428T133038, end_date=20250428T133039
[2025-04-28T13:30:39.420+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-28T13:30:39.425+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task transform_post (Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.; 1441)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 84, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/job_post.py", line 61, in job_post
    embedding = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 224, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/langchain_community/embeddings/huggingface.py", line 87, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence-transformers`.
[2025-04-28T13:30:39.481+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-04-28T13:30:39.512+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T13:30:39.515+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
